export const LOG_STATUS_PENDING = 'LOG_STATUS_PENDING';
export const LOG_STATUS_SUCCESS = 'LOG_STATUS_SUCCESS';
export const LOG_STATUS_FAILURE = 'LOG_STATUS_FAILURE';
export const LOG_STATUS_TIMEOUT = 'LOG_STATUS_TIMEOUT';
